### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by blazierkyle** [thomasrzhao/TRZNumberScrollView#1]
Hi,

This is a really neat library that I'm using in an app I'm working on. Thanks for putting in all the hard work!

It would be great to get this updated for Swift 3. I tried using the auto conversion tool but there are still a number of manual changes to make.

Thanks!

**Comment by thomasrzhao** [comment]
Updated for Swift 3 in commit 30aa0a2.

**Comment by blazierkyle** [comment]
Thanks for the super quick response!!
